name:  Name of the Catalog Entry
description: |
   Description of the Catalog Entry
version: 0.0.1-rancher1
category: wp
maintainer: Changlei Chen
license: Apache2
projectURL: http://192.168.6.74:8080/chenchanglei/rancher-demo.git
